PREFIX box: <http://fitlayout.github.io/ontology/render.owl#>
PREFIX segm: <http://fitlayout.github.io/ontology/segmentation.owl#>

SELECT ?s ?p ?o WHERE { ?s segm:hasTag ?o }

SELECT ?author ?title
WHERE { 
  ?a rdf:type segm:LogicalArea .
  ?t rdf:type segm:LogicalArea .
  ?a segm:isSubordinateTo ?t .
  ?a segm:hasText ?author .
  ?t segm:hasText ?title .
  ?a segm:hasTag segm:tag-ESWC--authors
}
